name: shorts
description: YouTube to Shorts Auto Editor - styleblue
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  in_app_purchase: ^3.1.13
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
